### ISSUE TITLE
[FakeDeafen] doesnt work

### ISSUE THREAD

**Issue by Masono03** [Tharki-God/BetterDiscordPlugins#80]
So i cant set a hotkey anymore neither does it show in the status picker anymore :(

Canary 165546 (d8c197e) Host 1.0.55 (28098) Windows 10 64-Bit (10.0.19044)

**Comment by Masono03** [comment]
Heres what the console says:
 [BetterDiscord] [Patcher] Could not fire before callback of ZP for FakeDeafen TypeError: Cannot read properties of undefined (reading 'children')
    at Object.eval [as callback] (betterdiscord://plugins/FakeDeafen.plugin.js:368:30)
    at <anonymous>:4:31093
    at ya (76e9a82e8b700619e599.js:1567:54)
    at bs (76e9a82e8b700619e599.js:1578:871)
    at gu (76e9a82e8b700619e599.js:1622:18)
    at mc (76e9a82e8b700619e599.js:1614:89)
    at Ic (76e9a82e8b700619e599.js:1614:17)
    at hc (76e9a82e8b700619e599.js:1613:867)
    at uc (76e9a82e8b700619e599.js:1610:983)
    at jo (76e9a82e8b700619e599.js:1550:577)
    at lc (76e9a82e8b700619e599.js:1611:498)
    at t.flushSync (76e9a82e8b700619e599.js:1633:496)
    at e.t.flushWaitQueue (76e9a82e8b700619e599.js:6902:257)
    at 76e9a82e8b700619e599.js:6902:155
    at new Promise (<anonymous>)
    at e.t.dispatch (76e9a82e8b700619e599.js:6902:43)
    at MessageLoggerV2.onDispatchEvent (betterdiscord://plugins/MessageLoggerV2.plugin.js:2601:218)
    at Object.eval [as callback] (betterdiscord://plugins/MessageLoggerV2.plugin.js:654:37)
    at e.dispatch (<anonymous>:4:31312)
    at /assets/2d1b4bd9dccba9987a35.js:1537:305
    at /assets/2d1b4bd9dccba9987a35.js:1536:414
    at Object.next (/assets/2d1b4bd9dccba9987a35.js:1536:519)
    at f (/assets/2d1b4bd9dccba9987a35.js:1535:379)
    at a (/assets/2d1b4bd9dccba9987a35.js:1537:486)

**Comment by Tharki-God** [comment]
will be fixed in next update

**Comment by Tharki-God** [comment]
and use code blocks when sharing errors

**Comment by Tharki-God** [comment]
should be fixed now
